### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pombredanne** [evandowling/net-geoip-gem#1]
Hi: Do you know what is the license for this Gem?
Thank you!

**Comment by evandowling** [comment]
I would think that it is the same as the net geo ip interface it relies upon: https://github.com/maxmind/geoip-api-c/blob/master/LICENSE

That said, I've not updated the bindings in a very long time and wouldn't be surprised if this gem is no longer compatibile with recent versions of that library.

**Comment by pombredanne** [comment]
@evandowling thank you ++ for the quick reply! that's good enough for me.
